import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'North Indian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'South Indian',
    color: Colors.amber,
  ),
  Category(
    id: 'c4',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category(
    id: 'c5',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c6',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c7',
    title: 'Desserts',
    color: Colors.lightGreen,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
      'c7',
    ],
    title: 'Jalebi',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://i.imgur.com/g7VsP2c.jpeg',
    duration: 40,
    ingredients: [
      'Maida: 1 cup (250 gm)',
      'Baking Powder: 1/2 tbsp',
      'Ghee or Butter: 1 tbsp',
      'Curd: 1/4 cup (60 ml)',
      'Water: 3/4 cup (approx 180 ml)',
      'Oil to fry',
      'Sugar Syrup: Sugar: 2 cups (500 gm)',
      'Water: 1 cup (250 ml)',
      'Green Cardamom pods: 2-3',
      'Saffron Food Color: a pinch',
      '1 small Lemon piece',
    ],
    steps: [
      'In a big bowl, take 1 cup of maida',
      'Add 1/2 tbsp of Baking Powder. You can also use half packet of eno or baking soda and citric acid in equal amount.',
      'Add 1 tbsp of ghee or clarified butter.',
      'Add curd to this. If you like extra sourness, use aged curd.',
      'Mix it all together without adding water first.',
      'Start adding water in batches.',
      'Whisk the batter until all the lumps are gone and batter turns smooth.',
      'We need a thick but pouring consistency for this recipe.',
      'Set this aside for 15 minutes.',
      'Place a pan on low flame and add 2 cups of sugar.',
      'Add 1 cup of water to this and set the flame on medium.',
      'Add two crushed cardamom pods. You can add kewra water or rose water as well.',
      'Add a piece of lemon. Doing this helps in stopping the crystallization of sugar syrup',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
      'c5',
    ],
    title: 'Broccoli and Mushroom Salad',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://preview.redd.it/yvcufhepxrg51.jpg?width=960&crop=smart&auto=webp&s=6bc9e628db4f0a117fb5cac9394f2b60eb7fbdd9',
    duration: 25,
    ingredients: [
      '1 Onion',
      '8 oz Mushrooms',
      '3 Carrots',
      '1 bunch Broccoli',
      '2 Egg',
      '2 tbsp Mayonnaise',
    ],
    steps: [
      'Chop up the broccoli, making sure to leave only the heads for the salad.',
      'Saute the chopped-up onion, then saute the finely-chopped raw mushrooms.',
      'Hard-boil an egg, also boil broccoli and carrots.',
      'Chop everything finely and mix with mayonnaise.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c7',
    ],
    title: 'Peanut and Chocolate Marble Cake',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://preview.redd.it/zufnysedl1g51.jpg?width=960&crop=smart&auto=webp&s=a6b95135e6a0030d007d6f2275fe96617b7aa5b1',
    duration: 160,
    ingredients: [
      '60 g butter (at room temperature), 1/3 cup',
      '110 g caster sugar, 1 cup',
      '50 g peanut butter, 1/4 cup',
      '15 g cocoa powder, 1/4 cup',
      '1 egg',
      'A pinch of salt',
      '90 g heavy cream, 1/2 cup',
      '95 g flour, 3/4 cup',
      '3 g baking powder, 1 tsp',
      '300g dark chocolate, 1 3/4 cups',
      '45g vegetable oil, 1/3 cup',
      '60g peanuts, 1/2 cup',
    ],
    steps: [
      'Mix sugar and soft butter (at room temperature). ',
      'Add the egg and cream and mix.',
      'Add flour, cocoa powder, salt and baking powder and mix until incorporated.',
      'Place in a pocket and set aside.',
      'In a cake mould, pipe the peanut cake in a W shape and the chocolate cake in an M shape on top and so on.',
      'Preheat the oven to 175°C (350 ° F) and bake for 1 hour to 1 hour 15 minutes depending on the oven.',
      'When taken out of the oven, leave to cool to temperature, then put in the freezer for 30 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c7',
    ],
    title: 'Donuts',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://c4.wallpaperflare.com/wallpaper/274/294/444/photography-of-stone-near-waterfalls-rainbow-wallpaper-preview.jpg',
    duration: 140,
    ingredients: [
      '2.5 cups flour',
      '1/4 cups sugar',
      '1/4 tsp salt',
      '2 1/4 tsp yeast',
      '2/3 cup warm milk',
      '3 Tbsp melted butter',
      '1 egg',
      '1/2 tsp vanilla extract',
    ],
    steps: [
      'Mix all ingredients and knead for 5-10 mins',
      'Cover and proof for about an 1 hour or doubled in size',
      'Roll out the dough and cut 2.5 inch circles (makes around 12)',
      'Cover and rest for another 45 mins',
      'Bake at 375F for 10-12 mins',
      'Brush with additional melted butter, roll in sugar, and fill as desired (cut a hole into the donuts and pipe in filling)',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c1',
    ],
    title: 'Dal Makhani',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.palatesdesire.com/wp-content/uploads/2018/12/Dal_Makhani.jpg',
    duration: 90,
    ingredients: [
      'Whole Urad (whole black lentils) : 1/2 cup (125 gm) (after soaking it doubles up)',
      'Rajma or Kidney beans : 2 Tbsp',
      'Butter : 100 gm',
      'Tomato Puree (preferably store bought) : 1.5 cups (375 ml)',
      'Ginger-Garlic Paste : 2 Tbsp',
      'Roasted Jeera Powder : 1/2 tbsp',
      'Garam Masala Powder : 1/2 tbsp',
      'Kashmiri Red Chilly Powder : 1.5 tbsp',
      'Some slit green chillies and ginger juliennes (optional)',
      'Fresh Cream : 200 gm',
      'Desi ghee : 3 spoons',
      'Some fresh coriander leaves.',
      'Salt to season.',
      'Water as required',
    ],
    steps: [
      'Take whole urad and clean it with water thoroughly atleast twice.',
      'Add 2 tablespoons of Rajma and let it soak with urad for 8 hours or overnight.',
      'Now take a pressure cooker and add urad and rajma to it and cook it for 20 whistles. Rajma and Urad gets soft yet holds the shape. This is exactly how we want it. Take it out.',
      'Now in a handi or a pressure cooker, add 3 spoons of desi ghee (clarified butter) and add 50 gm of butter. Adding ghee or oil prevents butter from getting burnt quickly.',
      'Add 2 tablespoons of ginger garlic paste and cook until raw smell goes away.',
      'Now add slit green chillies and ginger juliennes (optional).',
      'Add 1.5 cup of Tomato Puree and add salt to taste. Add cooked urad and rajma beans as well.',
      'Add 1/2 tbsp of roasted cumin powder.',
      'Add kashmiri red chilly powder.',
      'Mix it all well.',
      'Cover it and cook for an hour on low flame. If you\'re pressure cooking it, cook for 10-12 whistles.',
      'Open the lid, add 1/2 tbsp of garam masala powder.',
      'Add 50 gm more butter and 3/4 cup of fresh cream (you can also use cream collected off milk) and mix well.',
      'Cover and cook for 30-35 minutes more.',
      'Now open the lid and Dal would be thickened and become smooth in texture.',
      'Add finely chopped coriander leaves.',
      '(Optional) but to make it true restaurant style, add 20 gm of butter and 50 ml of fresh cream to top it off.',
      'Dal Makhani is ready. Garnish it with some cream and coriander leaves.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c5',
    ],
    title: 'Chicken Nuggets',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2015/4/8/4/WU1004H_Chicken-Nuggets_s4x3.jpg.rend.hgtvcom.616.462.suffix/1428675741536.jpeg',
    duration: 70,
    ingredients: [
      'Boneless chicken -½ kg',
      'White bread - 4 slice',
      'Garlic paste - ½ tablespoon',
      'Ginger paste - ½ tablespoon',
      'Soya sauce (optional)-1 tablespoon',
      'White pepper powder- ½ teaspoon',
      'Chilli powder - ½ teaspoon',
      'vegetable oil -1 ½ tablespoon',
      'Bread crumbs - 1 cup',
      'Milk - 1 tablespoon',
      'Egg - 1',
    ],
    steps: [
      'Take 4 slices of white bread and remove the sides. Only take white portions.',
      'Grind it in a mixer.',
      'Add washed boneless chicken,ginger garlic paste, white pepper powder, salt,soya sauce and chilli powder into the grinded bread in same mixer.',
      'Again grind these all in to a smooth paste.',
      'Take out the grinded paste and place it in counter top.',
      'Then add 1 ½ tablespoon of oil and knead well.',
      'Then roll it into thin sheet and cut into square pieces with a knife.',
      'Take an egg in a bowl and add white pepper ,mix it well with a fork.',
      'Add 1 tablespoon of milk into egg mixture and again mix well.',
      'Take each pieces of nuggets , dip it in egg mixture and then rolled in bread crumbs.',
      'Fry each coated nuggets in vegetable oil over low flame only (give sufficient time to cook the chicken)',
      'Fry until golden brown colour reached.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Banana Castella Cake',
    affordability: Affordability.Pricey,
    complexity: Complexity.Hard,
    imageUrl: 'https://i.redd.it/m2xymvftuze51.jpg',
    duration: 50,
    ingredients: [
      '56g All Purpose Flour',
      '14g Corn Flour',
      '40g Unsalted Butter',
      '4pcs Eggs （around 65g each included eggshell）',
      '40g Caster Sugar',
      '100g banana puree',
      '60ml milk',
      'A pinch of Salt',
      'A few drops of Lemon Juice or Vinegar',
    ],
    steps: [
      'Wash and cook banana leaves then wipe dry and put it in a tin.',
      'Put milk and butter in saucepan cook until 70°C.',
      'Pour the butter milk into the bowl with all purpose flour and corn starch which is already shifted then stir well.',
      'Mash bananas then pour it into the batter and stir well.',
      'Separate the eggs yolks and whites. Put the egg yolks into the batter and stir well.',
      'Add in few drops of lemon juice or vinegar and salt into egg whites and whipping it with high speed and add in sugar in portion (3 times), whisk until soft peak.',
      'Pour boiling water in a baking tray and put it in the oven, preheat oven to 150°C.',
      'Put 1/3 portion of egg whites into the batter and stir well for emulsification.',
      'Pour the batter into the egg whites bowl, use a spatula to draw a zigzag to remove air bubbles in the batter until smooth.',
      'Pour the batter from the top into the mould and bang the mould for few times to release the air bubbles.',
      'Water bath 150°C baking, use bottom heat for first 25 minutes then top and bottom heat for 45 minutes.',
      'When the cake is done must take it out and tear off the baking paper. Then cut it and enjoy it while it is still warm.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c1',
      'c2',
      'c4',
    ],
    title: 'Besan Ladoo',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://smedia2.intoday.in/aajtak/images/stories/092018/laddoo-pakwangali_520_092118125007.jpg?size=1200:675',
    duration: 40,
    ingredients: [
      'Desi Ghee (Clarified Butter) 150 gm',
      'Besan (Gram Flour) 250 gm',
      'Caster Sugar 500 gm',
      'Elaichi (Green Cardamom) Powder 1 teaspoon',
      'Pinch of yellow food color or turmeric.',
    ],
    steps: [
      'Heat a pan on low flame and add ghee to it.',
      'Add all of the besan and start mixing with a spatula.',
      'Keep mixing and roasting until it starts bubbling up and and a nutty aroma comes from it. This process takes nearly 15 minutes.',
      'Now add a pinch of food colour or turmeric powder to it and mix thoroughly.',
      'Turn off the flame and let the mixture cool down completely on room temperature.',
      'After it has cooled down, add sugar in batches and mix.',
      'You can use your hands to knead the mixture until it turns into a dough like state.',
      'After it has released oil, take a chunk of it and start rolling between your palms to make a round shape.',
      'Make all the balls like this and let them set for 10 minutes.',
      'Garnish them with silver leaves and chopped pistachios.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c7',
    ],
    title: 'Chocolate Banana Bread',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://preview.redd.it/70rcvhisc7e51.jpg?width=960&crop=smart&auto=webp&s=196cf32d2b4c949222f3fb6fc03ca5425baa05db',
    duration: 160,
    ingredients: [
      '2 ripe bananas',
      '1/3 cup (76g) salted butter - OR - 1/4 cup (62.5ml) vegetable oil',
      '1/3 cup (70g) granulated sugar',
      '1/3 cup (65g) brown sugar',
      '1 tsp vanilla',
      '1 egg',
      '1 tsp cinnamon',
      '1 tsp salt',
      '1 tsp baking soda',
      '1 1/4 cups (160g) flour',
      '1/2 cup (87.5g) dark chocolate',
    ],
    steps: [
      'Preheat the oven for 350°F (180°C)',
      'In one bowl, mash 2 ripe bananas',
      'Add in 1/3 cup (70g) granulated sugar, 1/3 cup (65g) brown sugar, 1/3 cup (76g) salted butter, 1 egg, and 1 tsp vanilla extract (these are the wet ingredients)',
      'Mix all the ingredients together well',
      'In another bowl, mix together 1 1/4 cups (160g) flour, 1 tsp cinnamon, 1 tsp baking soda, and 1 tsp salt (these are the dry ingredients)',
      'Slowly pour 1/4 portions of the dry ingredients into the wet ingredients, until fully combined',
      'Gently stir all of the ingredients together until just blended',
      'Add in 1/2 cup (87.5g) dark chocolate, and briefly stir',
      'I cut up a small dark chocolate bar, but you could use dark chocolate chips',
      'Grease a bread mould with cooking spray - OR - parchment paper',
      'Pour the dough into the bread mould',
      'Add some extra pieces of dark chocolate and brown sugar on top of the dough for some added oomph',
      'Bake the banana bread in the oven at 350°F (180°C) for 55 minutes, or until golden brown',
      'Take the banana bread of the oven, and let it cool for at least 20 minutes before consuming',
      'Enjoy!',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c6',
    ],
    title: 'Almond Berry Loaf',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://preview.redd.it/rdzx5iz82ld51.jpg?width=960&crop=smart&auto=webp&s=032b8bea50b280c4be3fb6b6ee61d10e0304bebd',
    duration: 120,
    ingredients: [
      'All-Purpose Flour (Maida) – 150 gms (1¼th cup)',
      'Baking Powder – 1 tsp',
      'Baking Soda – ½ tsp',
      'Milk – ½ cup',
      'Powdered Sugar – 125 gms (¾th cup)',
      'Butter (softened) – 60 gms (¼th cup)',
      'Olive Oil – 60 gms (¼th cup)',
      'Ground Almonds – 100 gms (¾th cup)',
      'Dried Berries – 70 gms (½ cup)',
    ],
    steps: [
      'Grease an 8×5-inch* loaf tin with butter/oil. Line with parchment paper or dust with flour and set it aside.',
      'Mix together the milk, butter, oil, sugar and vanilla essence and whisk them till light and fluffy.',
      'Sift the flour, baking soda and baking powder in another bowl.',
      'Gently fold the flour mixture and the almond powder in the milk mixture (wet ingredients) until combined (ensure that there are no lumps in the batter, but do not overbeat it).',
      'Preheat the oven to 180°C (350°F).',
      'Fold in the berries in the batter and pour the batter into the prepared loaf tin. Smoothen the surface of the batter.',
      'Bake for 35-40 minutes (the surface will develop cracks).',
      'Let it cool for 10 minutes before transferring it to a wire rack. Allow to cool to room temperature before slicing.',
      'Enjoy!',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c6',
      'c7',
    ],
    title: 'Milk Cookies',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://preview.redd.it/dpmlo76fena51.jpg?width=960&crop=smart&auto=webp&s=936126d6feb2a748b534cae90892742e5e0f3157',
    duration: 75,
    ingredients: [
      '1 Egg Yolk',
      '1 can (300ml) Condensed milk',
      '450g cornstarch',
      '1/4 cup (50g) sugar',
      '1/2 cup (113g) butter',
      '1 tsp Vanilla',
      '1 tsp salt',
      '1 tsp baking powder',
    ],
    steps: [
      'In one bowl, mix together 1/4 cup (50g) sugar, 450g cornstarch, 1 tsp salt, and 1 tsp baking powder (these are the dry ingredients)',
      'In another bowl, mix together 1 can (300ml) condensed milk, 1/2 butter, 1 tsp vanilla extract (these are the wet ingredients)',
      'Add in 1 egg yolk, and mix well',
      'Gradually pour the cornstarch mixture (the dry ingredients) into the condensed milk mixture (the wet ingredients)',
      'Use hands to further mix the dough until it becomes firm and smooth',
      'Grease a baking pan with cooking spray - OR - put parchment paper down on a baking pan',
      'Take out golf ball sized portions of dough, and roll them together between your palms to make a circular shape',
      'Bake the biscuits in the oven at 350°F (180°C) for 18-20 minutes',
      'Take them out of the oven, and let them cool for at least 20 minutes before consuming (or don’t… no judgement)',
      'Enjoy!',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c6',
    ],
    title: 'Strawberry Lemon Bars',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Hard,
    imageUrl:
        'https://preview.redd.it/8f3vhirk63851.jpg?width=960&crop=smart&auto=webp&s=d6d7958feeb9805748ccd3fcd36c81da7ea169ef',
    duration: 1200,
    ingredients: [
      '2 cups All-Purpose Flour',
      '1/2 cup Sugar',
      '1/2 tsp Salt',
      '1 cup Vegan Butter',
      '1 1/4 cup Lemon Juice',
      '2 cups Sugar',
      '1/4 tsp Salt',
      '1 3/4 cup Coconut Milk',
      '1 tsp vanilla extract',
      '1/2 cup 1 tbsp Cornstarch',
      '1 cup (230 grams) Strawberries',
      '1/8 tsp Turmeric or Vegan Yellow Food Coloring (Optional)',
    ],
    steps: [
      'Preheat the oven to 350° F. Prepare a 9 x 13 dish by spraying with nonstick spray and lining with parchment paper the hangs off the edges for easy removal later. ',
      'In a bowl add and mix the flour, sugar, and salt.',
      'Next, cut the vegan button into cubes or smaller pieces and add tp they dry ingredients. With your hands or a potato masher mix and press the ingredients together until it reaches a crumbly texture. Then press the dough together to form a dough ball. ',
      'Place the dough ball into the prepared pan. With your hand press the dough into pan until smooth and even. My edges were a bit thick, you can press the dough up along the side of the pan as well if you’d like. ',
      'Bake the crust in the oven for 20 minutes or until the edges become lightly browned. Once done remove from the oven and let it rest on the countertop. Leave the oven heat on since we will be baking the bars again. ',
      'While the crust is baking add the strawberries to a blender or food processor and blend until your left with a puree. Next, add 1 tbsp of the cornstarch to the puree and blend again so it’s thoroughly mixed in. ',
      'During or after the crust is has baked, add the lemon juice, sugar, vanilla extract, salt, coconut milk, remaining cornstarch, and optional turmeric or food coloring to a saucepan and whisk until the ingredients are well combined.',
      'Over medium heat using silicone or wooden spoon continue to stir the mixture while it heats and thickens. Make sure to stir the bottom of the pan to help the sugar and cornstarch melted and mix into the rest of the ingredients. Once the mixture has significantly thickened, pour ¾ of it onto the crust in an even layer.',
      'Add the pureed strawberry mixture into the remaining lemon filling. Mix and heat the mixture a bit longer until it’s properly thickened again after adding the strawberry puree. My strawberry mixture didn’t get quite as thick as the lemon layer, but it will set just the same.',
      'Next, add the strawberry fillings on top of the lemon layer. ',
      'Return the pan to the oven and cook the bars for 20 minutes at 350 degrees.',
      'Once cooked remove from the oven and allow it to cool on a countertop for around an hour. After place the pan into the fridge for at least 2 hours to properly cool and set. The longer it chills the more it will firm. ',
      'Once chilled remove the bars from the pan by pulling it up by the overhanging parchment paper.',
      'Place on a cutting board and cut the bar into at least 24 squares. Sprinkle with powdered sugar or top with lemon and strawberry slices. Store in an airtight container in the fridge for up to 5 days.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c3',
    ],
    title: 'Idli',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Hard,
    imageUrl:
        'https://navbharattimes.indiatimes.com/hindi-recipes/wp-content/uploads/sites/2/2018/09/idli-655x477.jpg',
    duration: 500,
    ingredients: [
      '1 cup regular rice, 190 to 200 grams (sona masoori rice or parmal rice or basmati rice)',
      '1 cup parboiled rice or idli rice, 200 grams',
      '½ cup whole or split urad dal/black gram, husked, 120 grams',
      '¼ cup thick poha/flattened rice, 20 grams',
      '¼ tsp methi seeds/fenugreek seeds',
      '2 cups water for soaking rice',
      '1 cup water for soaking urad dal',
      '½ cup water for grinding urad dal or add as required',
      '¾ cup water for grinding rice or add as required',
      '1 tsp rock salt',
      'oil as required to apply to the idli moulds',
      '2.5 cups water for steaming idlis',
    ],
    steps: [
      'Soaking:',
      'Pick and rinse both the regular rice and parboiled rice.',
      'Einse the poha and add to the rice.',
      'Add water. mix well. cover and keep the rice + poha to soak for 4 to 5 hours.',
      'In a separate bowl, rinse the urad dal and methi seeds a couple of times.',
      'Soak the urad dal with methi seeds separately in water for 4-5 hours.',
      'Grinding:',
      'Drain the soaked urad dal. reserve the water.',
      'Grind the urad dal, methi seed with ¼ cup of the reserved water for some seconds. then add remaining ¼ cup water. grind till you get a smooth and fluffy batter.',
      'Remove the urad dal batter in a bowl and keep aside.',
      'Grind the rice in batches to make a smooth batter.',
      'Mix both the batters together in a large bowl or pan. add salt and mix well.',
      'Cover and let the batter ferment for 8-9 hours or more if required. after the fermentation process is over, the batter will become double in size and rise.',
      'Steaming:',
      'Grease the idli moulds. pour the batter in the moulds and steam the idlis in a pressure cooker or steamer.',
      'If using pressure cooker remove the vent weight.whistle. steam for 10-12 mins or until the idlis are done.',
      'Serve the steaming hot idlis with coconut chutney and sambar. remaining batter can be stored in the refrigerator for a couple of days.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];
